version: '3.8'

services:
  postgres:
    container_name: postgres_db
    image: postgres:alpine
    restart:
      always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: danu
      POSTGRES_PASSWORD: macrii
    volumes:
      - ./db-data/:/var/lib/postgresql/data/

  redis:
    container_name: redis_db
    image: redis:alpine
    restart:
      always
    volumes:
      - ./db-data/:/var/lib/redis/data/
    ports:
      - "6379:6379"


volumes:
  postgres-db:
    driver: local
  redis-db:
    driver: local